version: '2'
services:
    brokensvc-app:
        image: brokensvc
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://brokensvc-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=brokensvc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    brokensvc-mongodb:
        extends:
            file: mongodb.yml
            service: brokensvc-mongodb
